version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql:/var/lib/mysql
  
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - "9000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  # npm:
  #   image: node:current-alpine
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./src:/var/www/html
  #   entrypoint: ["npm", "i", "-g", "dev"]
  #   depends_on:
  #     - php
  #     - python
  

  node:
    build: 
      context: .
      dockerfile: node.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm", "i", "-g", "dev"]
    depends_on:
      - php
  
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
      - php
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379